Fix: lambda invocation trigger
fulll/terraform-aws-lambda pull request #26
Opened 2022-06-24 13:20 UTC by aputzufulll

2022-06-24 13:21 UTC, vibou requested changes
A question regarding the `package_type` variable

2022-06-24 13:21 UTC, vibou commented on lambda.tf
> +    redeployment = filebase64sha256(var.image_uri == null ? var.lambda_filepath : var.image_uri)
please remove the `package_type` variable then which shouldn't be used anywhere else is it?

2022-06-24 13:26 UTC, aputzufulll commented on lambda.tf
> +    redeployment = filebase64sha256(var.image_uri == null ? var.lambda_filepath : var.image_uri)
`package_type` is used in the lambda function :
```
  source_code_hash = var.package_type != "Zip" ? null : filebase64sha256(var.lambda_filepath)
  publish = var.lambda_publish
  s3_bucket     = var.package_type != "Zip" ? null : data.aws_s3_bucket.deployment_bucket[0].id
  s3_key        = var.package_type != "Zip" ? null : var.lambda_bucket_key
  image_uri     = var.package_type != "Zip" ? var.image_uri : null
  package_type  = var.package_type
```

2022-06-27 09:28 UTC, vibou commented on lambda.tf
> +    redeployment = filebase64sha256(var.image_uri == null ? var.lambda_filepath : var.image_uri)
package type can be removed and use a condition based on image_uri

2022-06-27 15:43 UTC, vibou approved these changes

2022-06-29 07:16 UTC, merged